### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by wilsonlow22** [wilsonlow22/github-crash-course#1]
I think it look better if the main title is a bit more orange

```css
   h1 {
      color: #efa82e
   }
```
